create table public.clients (
    id bigint generated by default as identity not null,
    created_at timestamptz not null default now(),
    user_telegram_id varchar not null,
    first_name varchar,
    last_name varchar,
    last_message_at timestamptz not null default now(),
    constraint clients_pkey primary key (id),
    constraint clients_user_telegram_id_key unique (user_telegram_id)
);

create table public.messages (
    id bigint generated by default as identity not null,
    created_at timestamptz not null default now(),
    author varchar,
    body text,
    messenger_user_id varchar,
    messenger_type varchar,
    client_id bigint not null,
    constraint messages_pkey primary key (id),
    constraint messages_client_id_fkey
        foreign key (client_id)
        references public.clients (id)
);

create index clients_last_message_at_idx
    on public.clients (last_message_at desc);

create index messages_created_at_idx
    on public.messages (created_at desc);

alter table public.clients enable row level security;
alter table public.messages enable row level security;

revoke all on table public.clients from anon, authenticated;
revoke all on table public.messages from anon, authenticated;

grant select, insert, update, delete on table public.clients to service_role;
grant select, insert, update, delete on table public.messages to service_role;

grant usage, select on sequence public.clients_id_seq to service_role;
grant usage, select on sequence public.messages_id_seq to service_role;

create or replace function public.save_message(
    p_user_telegram_id varchar,
    p_first_name varchar,
    p_last_name varchar,
    p_author varchar,
    p_body text,
    p_messenger_type varchar,
    p_created_at timestamptz default now()
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_client_id bigint;
    v_message_id bigint;
begin
    insert into public.clients (
        user_telegram_id,
        first_name,
        last_name,
        last_message_at
    )
    values (
        p_user_telegram_id,
        p_first_name,
        p_last_name,
        p_created_at
    )
    on conflict (user_telegram_id) do update
    set
        first_name = excluded.first_name,
        last_name = excluded.last_name,
        last_message_at = greatest(
            clients.last_message_at,
            excluded.last_message_at
        )
    returning id into v_client_id;

    insert into public.messages (
        created_at,
        author,
        body,
        messenger_user_id,
        messenger_type,
        client_id
    )
    values (
        p_created_at,
        p_author,
        p_body,
        p_user_telegram_id,
        p_messenger_type,
        v_client_id
    )
    returning id into v_message_id;

    return v_message_id;
end;
$$;

revoke all on function public.save_message(
    varchar,
    varchar,
    varchar,
    varchar,
    text,
    varchar,
    timestamptz
) from public;

grant execute on function public.save_message(
    varchar,
    varchar,
    varchar,
    varchar,
    text,
    varchar,
    timestamptz
) to service_role;
